#!/usr/bin/python3
    """_summary_
        parses logs generated by a py script
        format o logs: 
        <IP Address> - [<date>] "GET /projects/260 HTTP/1.1" <status code> <file size>
    Returns:
        prints count of status codes along with file size
    """

from sys import stdin
from collections import counter
import re
#import termios

def define_stats():
    '''return the data organized with counter'''
    try:
        for line in stdin:
          regex = r'\d{3}\s\d{1,4}'
          data = re.findall(regex, line)
          return(counter(data).sort())
    except KeyboardInterrupt:
        pass
    #termios.tcflush(stdin, termios.TCIOFLUSH)
  
def print_stats():
    '''print the data using the counter method'''
    data = define_stats()
    n = 0
    for i in data:
        i.split(" ")
        if len(i) == 2:
            if(n == 10):
                print("File size:{:d}".format(int(i[-1])))
                n = 0
        else:
            pass
        print("{:d}: {:d}".format(i, data[i]))
        n += 1
              
if "__name__" == "__main__":
    '''main block'''
    print_stats()
    